<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Article;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentByArticle(Article $article)
    {
        $qb = $this->createQueryBuilder('c');

        $qb->where('c.enabled = :enabled')
            ->setParameter('enabled', true)
            ->join('c.article', 'ca')
            ->andWhere('ca = :article')
            ->setParameter('article', $article)
            ->orderBy('c.date', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
