<?php

namespace AppBundle\Repository;

/**
 * SnowboarderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnowboarderRepository extends \Doctrine\ORM\EntityRepository
{
}
